name: Sync-Code

on:
  push:
    branches:
      - main

env:
  git_portable_win_version: "v0.0.1"

jobs:
  push-to-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        run: |
          git init
          git remote add origin https://github.com/${GITHUB_REPOSITORY}.git
          git fetch --all
          for branch in `git branch -a | grep remotes | grep -v HEAD`; do
            git branch --track ${branch##*/} $branch
          done
        env:
          GITHUB_REPOSITORY: moxying/git-portable-win

      - name: Push to gitcode
        run: |
          remote_repo="https://oauth2:${GITCODE_ACCESS_TOKEN}@gitcode.com/${GITCODE_REPOSITORY}.git"

          git remote add gitcode "${remote_repo}"
          git show-ref # useful for debugging
          git branch --verbose

          # publish all
          git push --all --force gitcode
          git push --tags --force gitcode
        env:
          GITCODE_REPOSITORY: moxying/git-portable-win
          GITCODE_ACCESS_TOKEN: ${{ secrets.GITCODE_ACCESS_TOKEN}}

      - name: "checkout git-portable-win"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: ${{ github.repository }}
          path: git-portable-win

      - name: "package git"
        shell: bash
        run: |
          ls
          pwd
          cd git-portable-win
          zip -r git_portable_win_${{ env.git_portable_win_version }}.zip ./*
          cd ..

      - name: "prepare python 3.10"
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: "upload model to modelscope"
        shell: bash
        run: |
          pwd
          ls
          pip install modelscope

          # ha ha ha ..
          mv git-portable-win/.github/modelscope .
          mv git-portable-win/git_portable_win_${{ env.git_portable_win_version }}.zip modelscope/model-template/
          cd modelscope
          python upload_model.py
        env:
          MODELSCOPE_ACCESS_TOKEN: ${{ secrets.MODELSCOPE_ACCESS_TOKEN }}
          MODELSCOPE_MODEL_ID: moxying/base-git-model-${{ env.git_portable_win_version }}
          MODELSCOPE_MODEL_DIR: model-template
